-- H2-compatible schema with quoted identifiers to match Spring Data JDBC generated SQL
DROP TABLE IF EXISTS "comments";
DROP TABLE IF EXISTS "posts";

CREATE TABLE "posts" (
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "title" VARCHAR(255) NOT NULL,
    "text" CLOB NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    "likes_count" INTEGER NOT NULL,
    "comments_count" INTEGER NOT NULL,
    "image_path" VARCHAR(500),
    "tags" VARCHAR ARRAY
);

CREATE TABLE "comments" (
    "ID" BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "text" CLOB NOT NULL,
    "post_id" BIGINT NOT NULL,
    "created_at" TIMESTAMP NOT NULL,
    "updated_at" TIMESTAMP NOT NULL,
    CONSTRAINT fk_comments_post FOREIGN KEY ("post_id") REFERENCES "posts"("ID") ON DELETE CASCADE
);
